backend:
  name: github
  repo: GradyWaters/ethpublic-factory
  branch: main
  base_url: https://ethpublic-cms-oauth.jonaretakis.workers.dev
  auth_endpoint: /auth

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: posts
    label: Posts
    folder: src/content/posts
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Publish Date, name: pubDate, widget: datetime }
      - { label: Category, name: category, widget: string }
      - { label: Body, name: body, widget: markdown }
